### ISSUE TITLE
[doc] connectors and pinout

### ISSUE THREAD

**Issue by josuah** [tinyvision-ai-inc/tinyclunx33_public#1]
Currently, locating the connectors on the devboard is a bit challenging to figure out.
A photo with an overlay drawing could help, or something like this:
https://pico-ice.tinyvision.ai/md_pinout.html

**Comment by josuah** [comment]
Alternatively, some kind of text table looking like a config file could help making things easy to understand, and use as part of a script.

Maybe the way it was done here:

**Comment by josuah** [comment]
https://github.com/tinyvision-ai-inc/pico-ice/blob/main/Docs/pinout/data.py

**Comment by josuah** [comment]
material needed
- [ ] schematic to use of the Devkit v2
- [ ] schematic to use for the SoM v2
- [ ] hq photo of the board for overlay
- [ ] model of the [pico-ice](https://github.com/tinyvision-ai-inc/pico-ice/blob/main/Docs/pinout/data.py)

**Comment by josuah** [comment]
![Image](https://github.com/tinyvision-ai-inc/tinyclunx33_public/assets/55351021/d77b614c-51c7-4905-a230-323ac469b728)

**Comment by alanridel** [comment]
[pinout_diagram.zip](https://github.com/user-attachments/files/15899792/pinout_diagram.zip)

Board image, Python code along with make file included in the zip. Please let me know if any additional changes needed.

**Comment by josuah** [comment]
![pinout](https://github.com/tinyvision-ai-inc/tinyclunx33_public/assets/55351021/5b51e26a-674e-4fcd-8f94-efbaacf5ad9a)
From above...

**Comment by josuah** [comment]
Nice! Already possible to add this to the doc...
It can also help to have the documentation for the jumpers: J7, J10, J11, J12, J13  which can help with knowing how to place it.
These might evolve for v3, but then the diagram can evolve accordingly.
The v2 is already shipped to the clients, so this is the one that needs the most doc for now.

**Comment by josuah** [comment]
It is also possible to start integrating it into the doc:
add that `pinout` directory to https://github.com/tinyvision-ai-inc/tinyclunx33_public/tree/main/Docs and make a PR for instance? Also including the `.png` file so that it is not required to run the Makefile when the website is built.

**Comment by alanridel** [comment]
![pinout](https://github.com/tinyvision-ai-inc/tinyclunx33_public/assets/171654395/18de767b-b57b-4ae8-89f9-4d628a9d6f6b)

this is the updated pinout diagram. Josuah can you explain me the PR procedure for this repo?

**Comment by josuah** [comment]
fixed by #4

**Comment by josuah** [comment]
Next is to add it to the website.

**Comment by josuah** [comment]
The Rev3 image is still having "Rev2" written on it. Maybe this can be put on hold until a new Rev3 is done?

**Comment by vr2045** [comment]
We can add a sticker to this to change the rev2 to a rev3. Alternatively, we could change our docs so it calls this out as rev2 (since really, no one received rev1 except Josuah and myself).

**Comment by josuah** [comment]
The naming change is done, and this allows to use the unmodified board without sticker: the image for Rev3 is good as well.

**Comment by josuah** [comment]
![](https://tinyclunx33.tinyvision.ai/tinyCLUNX33_MIPI_to_USB3_devkit_Rev2_photo_front.jpg)

**Comment by alanridel** [comment]
![Image](https://github.com/user-attachments/assets/9c0c763f-8a5d-4ccb-9f0d-8a3e269adfb0)

Pinout diagram for tinyCLUNX33 dev_kit_v2. Please check and let me know if any changes needed.

**Comment by josuah** [comment]
Adjusted the background, took new screenshots with adjusted window size, and published them online.
